import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href="/"> Home</a>
          <a href="events"> Events</a>
          <a href="about-us"> About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((eve) => (
          <a key={eve.id} href={`/events/${eve.id}`}>
            <Image src={eve.image} alt={eve.title} width={200} height={100}/> <h2> {eve.title}</h2>{" "}
            <p> {eve.description}</p>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>Footer</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
